/// Enum representing the books of the Bible in canonical order (Old and New Testament).
/// Each variant corresponds to a book, with explicit indices starting from 1 for Genesis.
pub(crate) enum BookIndex {
    Genesis = 1,
    Exodus,
    Leviticus,
    Numbers,
    Deuteronomy,
    Joshua,
    Judges,
    Ruth,
    FirstSamuel,
    SecondSamuel,
    FirstKings,
    SecondKings,
    FirstChronicles,
    SecondChronicles,
    Ezra,
    Nehemiah,
    Esther,
    Job,
    Psalms,
    Proverbs,
    Ecclesiastes,
    SongOfSolomon,
    Isaiah,
    Jeremiah,
    Lamentations,
    Ezekiel,
    Daniel,
    Hosea,
    Joel,
    Amos,
    Obadiah,
    Jonah,
    Micah,
    Nahum,
    Habakkuk,
    Zephaniah,
    Haggai,
    Zechariah,
    Malachi,
    // New Testament
    Matthew,
    Mark,
    Luke,
    John,
    Acts,
    Romans,
    FirstCorinthians,
    SecondCorinthians,
    Galatians,
    Ephesians,
    Philippians,
    Colossians,
    FirstThessalonians,
    SecondThessalonians,
    FirstTimothy,
    SecondTimothy,
    Titus,
    Philemon,
    Hebrews,
    James,
    FirstPeter,
    SecondPeter,
    FirstJohn,
    SecondJohn,
    ThirdJohn,
    Jude,
    Revelation,
}

impl BookIndex {
    pub(crate) fn from_index(value: u8) -> Option<Self> {
        match value {
            1 => Some(BookIndex::Genesis),
            2 => Some(BookIndex::Exodus),
            3 => Some(BookIndex::Leviticus),
            4 => Some(BookIndex::Numbers),
            5 => Some(BookIndex::Deuteronomy),
            6 => Some(BookIndex::Joshua),
            7 => Some(BookIndex::Judges),
            8 => Some(BookIndex::Ruth),
            9 => Some(BookIndex::FirstSamuel),
            10 => Some(BookIndex::SecondSamuel),
            11 => Some(BookIndex::FirstKings),
            12 => Some(BookIndex::SecondKings),
            13 => Some(BookIndex::FirstChronicles),
            14 => Some(BookIndex::SecondChronicles),
            15 => Some(BookIndex::Ezra),
            16 => Some(BookIndex::Nehemiah),
            17 => Some(BookIndex::Esther),
            18 => Some(BookIndex::Job),
            19 => Some(BookIndex::Psalms),
            20 => Some(BookIndex::Proverbs),
            21 => Some(BookIndex::Ecclesiastes),
            22 => Some(BookIndex::SongOfSolomon),
            23 => Some(BookIndex::Isaiah),
            24 => Some(BookIndex::Jeremiah),
            25 => Some(BookIndex::Lamentations),
            26 => Some(BookIndex::Ezekiel),
            27 => Some(BookIndex::Daniel),
            28 => Some(BookIndex::Hosea),
            29 => Some(BookIndex::Joel),
            30 => Some(BookIndex::Amos),
            31 => Some(BookIndex::Obadiah),
            32 => Some(BookIndex::Jonah),
            33 => Some(BookIndex::Micah),
            34 => Some(BookIndex::Nahum),
            35 => Some(BookIndex::Habakkuk),
            36 => Some(BookIndex::Zephaniah),
            37 => Some(BookIndex::Haggai),
            38 => Some(BookIndex::Zechariah),
            39 => Some(BookIndex::Malachi),
            40 => Some(BookIndex::Matthew),
            41 => Some(BookIndex::Mark),
            42 => Some(BookIndex::Luke),
            43 => Some(BookIndex::John),
            44 => Some(BookIndex::Acts),
            45 => Some(BookIndex::Romans),
            46 => Some(BookIndex::FirstCorinthians),
            47 => Some(BookIndex::SecondCorinthians),
            48 => Some(BookIndex::Galatians),
            49 => Some(BookIndex::Ephesians),
            50 => Some(BookIndex::Philippians),
            51 => Some(BookIndex::Colossians),
            52 => Some(BookIndex::FirstThessalonians),
            53 => Some(BookIndex::SecondThessalonians),
            54 => Some(BookIndex::FirstTimothy),
            55 => Some(BookIndex::SecondTimothy),
            56 => Some(BookIndex::Titus),
            57 => Some(BookIndex::Philemon),
            58 => Some(BookIndex::Hebrews),
            59 => Some(BookIndex::James),
            60 => Some(BookIndex::FirstPeter),
            61 => Some(BookIndex::SecondPeter),
            62 => Some(BookIndex::FirstJohn),
            63 => Some(BookIndex::SecondJohn),
            64 => Some(BookIndex::ThirdJohn),
            65 => Some(BookIndex::Jude),
            66 => Some(BookIndex::Revelation),
            _ => None,
        }
    }
}
