use crate::{BookName, Edition};

impl BookName {
    pub fn from_index(value: u8) -> Option<Self> {
        match value {
            1 => Some(BookName::Genesis),
            2 => Some(BookName::Exodus),
            3 => Some(BookName::Leviticus),
            4 => Some(BookName::Numbers),
            5 => Some(BookName::Deuteronomy),
            6 => Some(BookName::Joshua),
            7 => Some(BookName::Judges),
            8 => Some(BookName::Ruth),
            9 => Some(BookName::FirstSamuel),
            10 => Some(BookName::SecondSamuel),
            11 => Some(BookName::FirstKings),
            12 => Some(BookName::SecondKings),
            13 => Some(BookName::FirstChronicles),
            14 => Some(BookName::SecondChronicles),
            15 => Some(BookName::Ezra),
            16 => Some(BookName::Nehemiah),
            17 => Some(BookName::Esther),
            18 => Some(BookName::Job),
            19 => Some(BookName::Psalms),
            20 => Some(BookName::Proverbs),
            21 => Some(BookName::Ecclesiastes),
            22 => Some(BookName::SongOfSolomon),
            23 => Some(BookName::Isaiah),
            24 => Some(BookName::Jeremiah),
            25 => Some(BookName::Lamentations),
            26 => Some(BookName::Ezekiel),
            27 => Some(BookName::Daniel),
            28 => Some(BookName::Hosea),
            29 => Some(BookName::Joel),
            30 => Some(BookName::Amos),
            31 => Some(BookName::Obadiah),
            32 => Some(BookName::Jonah),
            33 => Some(BookName::Micah),
            34 => Some(BookName::Nahum),
            35 => Some(BookName::Habakkuk),
            36 => Some(BookName::Zephaniah),
            37 => Some(BookName::Haggai),
            38 => Some(BookName::Zechariah),
            39 => Some(BookName::Malachi),
            40 => Some(BookName::Matthew),
            41 => Some(BookName::Mark),
            42 => Some(BookName::Luke),
            43 => Some(BookName::John),
            44 => Some(BookName::Acts),
            45 => Some(BookName::Romans),
            46 => Some(BookName::FirstCorinthians),
            47 => Some(BookName::SecondCorinthians),
            48 => Some(BookName::Galatians),
            49 => Some(BookName::Ephesians),
            50 => Some(BookName::Philippians),
            51 => Some(BookName::Colossians),
            52 => Some(BookName::FirstThessalonians),
            53 => Some(BookName::SecondThessalonians),
            54 => Some(BookName::FirstTimothy),
            55 => Some(BookName::SecondTimothy),
            56 => Some(BookName::Titus),
            57 => Some(BookName::Philemon),
            58 => Some(BookName::Hebrews),
            59 => Some(BookName::James),
            60 => Some(BookName::FirstPeter),
            61 => Some(BookName::SecondPeter),
            62 => Some(BookName::FirstJohn),
            63 => Some(BookName::SecondJohn),
            64 => Some(BookName::ThirdJohn),
            65 => Some(BookName::Jude),
            66 => Some(BookName::Revelation),
            _ => None,
        }
    }
}

/// Match Bible file names (without extension) to Edition
/// Panics if called with an unknown file. Not meant to
/// be called by users of this crate
pub fn filestem_to_edition(file_name: &str) -> Edition {
    match file_name {
        "EnglishASVBible" => Edition::EnglishASV,
        "EnglishKJBible" => Edition::EnglishKingJames,
        _ => panic!("Unknown edition: {}", file_name),
    }
}
